#! /bin/bash

# if语句事实上判断的是程序的返回值，返回值0表示真，非0表示假
if ./testscript -1		##如果返回值是-1
then
	echo "testscript exit -1"
fi

if ./testscript 0		##如果返回值是0
then
	echo "testscript exit 0"
fi

if ./testscript 1		##如果返回值是1
then
	echo "testscript exit 1"
fi
