#! /bin/bash

# 如果char_equal在当前目录存在且可执行，就执行这个脚本
if [ -x char_equal ]
then
	./char_equal
fi

# test和[命令在数字比较方面只能用来比较整数(正整数和负整数)

# 如果$@变量(也就是用户输入的参数)对应的文件存在
# 并且 /usr/bin/vi文件可执行，则执行if里面的语句
# -a表示条件与，和使用&&一样的效果
if [ -f $@ -a -x /usr/bin/vi ]
then
	cp $@ $@.bak
	vi $@
fi

if [ -f $@ ] && [ -x /usr/bin/vi ]
then
	cp $@ $@.bak
	vi $@
fi
