#! /bin/bash
# readfunc

if [ -r backfunc ]
then
	# source the file
	. backfunc
else
	echo "$`basename $0` cannot locate backfunc file"
fi

echo -n "Enter the code name: "
read CODE
# does the code entered match the code from backfunc file???
if [ "${CODE}" != "${_CODE}" ]
then
	echo "Wrong code...exiting..will use defaults"
	exit 1
fi

echo "The environment config file reprots"
echo "Full backup Required				: $_FULLBACKUP"
echo "The Logfile is					: $_LOGFILE"
echo "The Device To Backup To is		: $_DEVICE"
echo "You Are To Be Informed by Mail	: $_INFORM"
echo "A Statistic Report To Be Printed  : $_PRINT_STATS"
