# this is a makefile to verify the default aim

# envir_1称为make的终极目标
include envir_make

# 自动化变量 $@会被 make 自动展开为目标名称
# 一般情况下 makefile 的终极目标是第一条规则的目标
aim_1:
	@echo "this is " $@

aim_2:
	@echo "this is " $@

aim_3:
	@echo "this is " $@
