#!/bin/bash
for var in A B C
do
	echo "var is $var"
done

# $*该变量包含了所有输入的命令行参数值
for rpmpackage in $*
do
	if [ -r "$rpmpackage" ]
	then
		echo "$rpmpackage this file can read"
	else
		echo "ERROR:cannot read file $rpmpackage"
	fi
done

# 换行
echo
# 打印当前目录下的所有jpg文件
echo *.jpg

# 引号(单引号和双引号)可以防止这种通配符扩展
# 双引号可以防止通配符扩展但允许变量扩展
# 单引号可以防止任何变量扩展
echo "*.jpg"
echo '*.jpg'
echo "$var"	# C
echo '$var'	# $var
echo $SHELL
echo "$SHELL"
echo '$SHELL'

# 使用转义字符防止通配符扩展
echo \*.jpg
echo \$SHELL
