#!/bin/bash
# we have less than 3 arguments. Print the help text:
# $#包含参数的个数
echo $#
echo $*
if [ $# -lt 3 ]
then
cat << HELP
ren -- renames a number o files using sed regular expressions
USAGE:ren 'regexp''replacement'files...
EXAMPLE:rename all *.HTM files in *.html:
ren 'HTM$''HTML'*.HTM
HELP
	exit 0
fi

OLD="$1"
NEW="$2"
# The shift command removes one argument from the list of
# command line arguments
shift
shift
# $* contains now all the files:
for file in $*
do
	# -f判断文件是否存在
	if [ -f "$file" ]
	then
		# 通过sed命令搜索和替换来产生新的文件名
		newfile=`echo "$file" | sed "s/${OLD}/${NEW}/g"`
		if [ -f "$newfile" ]
		then
			echo "ERROR: $newfile exists already"
		else
			echo "renaming $file to $newfile..."
			mv "$file" "$newfile"
		fi
	fi
done
