#!/bin/bash

# 使用-n选项禁止echo命令输出后换行
echo -n "What is your name:"
read name
echo "you input is $name"

echo $HOME
# 执行tty命令
echo "`tty`"
# empty line
echo 
# empty line, -e是的转义字符生效
echo -e "\n"
echo "\""

echo "input two str:"
read fir sec
echo "fir: $fir sec: $sec"
