#! /bin/bash
# forparam
# 在f o r循环中省去i n列表选项时，它将接受命令行位置参数作为参数。实际上即指明
# for params in "$@" 或者 for params in "$*"

for params
do
	echo "You supplied $params as a command line option"
done
echo

for params in "$@"
do
	echo "You supplied $params as a command line option"
done
