#! /bin/bash
#iftest
# this is a comment line, all comment lines start with a #
if [ "10" -lt "12" ]
then
	# yes 10 is less than 12
	echo "Yes, 10 is less than 12"
fi

echo -n "Enter your name: "
read NAME
# did the user just hit return ????
if [ "$NAME" == "" ]
then
	echo "You did not enter any information"
fi
